[package]
name    = "wifi"
version = "0.1.2"
edition = "2021"

[dependencies]
anyhow      = "1.0.94"
esp-idf-svc = "0.49"
heapless = "0.8.0"
log         = "0.4"

[build-dependencies]
embuild = "0.32"

[dev-dependencies]
toml-cfg = "0.2.0"
